insert into discipline (discipline, ref_activite) values ('tennis', 2);
insert into categories (discipline, ref_activite) values ('squash', 2);
insert into categories (discipline, ref_activite) values ('badminton', 2);
insert into categories (discipline, ref_activite) values ()'tennis de table', 2);
insert into categories (discipline, ref_activite) values ('volley-ball', 2);
insert into categories (discipline, ref_activite) values ('natation', 3);
insert into categories (discipline, ref_activite) values ('water-polo', 3);
insert into categories (discipline, ref_activite) values ('patin a glace', 4);
insert into categories (discipline, ref_activite) values ('hockey sur glace', 4);
insert into categories (discipline, ref_activite) values ('handball', 6);
insert into categories (discipline, ref_activite) values ('gymnastique', 5);
insert into categories (discipline, ref_activite) values ('basket-ball', 6);
insert into categories (discipline, ref_activite) values ('athletisme', 7);
insert into categories (discipline, ref_activite) values ('football', 7);
