insert into categories (categorie, discipline, ref_activite) values ('salle', 'tennis', 2);
insert into categories (categorie, discipline, ref_activite) values ('salle', 'squash', 2);
insert into categories (categorie, discipline, ref_activite) values ('salle', 'badminton', 2);
insert into categories (structure, discipline, ref_activite) values ('salle', 'tennis de table', 2);
insert into categories (structure, discipline, ref_activite) values ('salle', 'volley-ball', 2);
insert into categories (structure, discipline, ref_activite) values ('piscine', 'natation', 3);
insert into categories (structure, discipline, ref_activite) values ('piscine', 'water-polo', 3);
insert into categories (structure, discipline, ref_activite) values ('patinoire', 'patin a glace', 4);
insert into categories (structure, discipline, ref_activite) values ('patinoire', 'hockey sur glace', 4);
insert into categories (structure, discipline, ref_activite) values ('gymnase', 'handball', 5);
insert into categories (structure, discipline, ref_activite) values ('gymnase', 'gymnastique', 4);
insert into categories (structure, discipline, ref_activite) values ('gymnase', 'basket-ball', 4);
insert into categories (structure, discipline, ref_activite) values ('stade', 'athletisme', 5);
insert into categories (structure, discipline, ref_activite) values ('stade', 'football', 5);
